### ISSUE TITLE
Write draft ggplot satellites

### ISSUE THREAD

**Issue by MathildeMousset** [epicentre-msf/repicentre#30]
I am a bit vague here because I am still thinking about what to add.

**Comment by MathildeMousset** [comment]
I have so many urgent ones: dynamic aes, scales, dates on epicurves...

**Comment by ceisenhauer** [comment]
unclear what this issue is. is this a discussion or a task ? consider closing and reformatting into individual tasks / discussion(s) as appropriate

**Comment by MathildeMousset** [comment]
The drafts that were in it were moved to their own branches and issues.
