### ISSUE TITLE
write guide for session reviews

### ISSUE THREAD

**Issue by ceisenhauer** [epicentre-msf/repicentre#48]
this should be a short and simple guide explaining how to use whatever revew method we settle upon (ex github dev, hypothesis, etc.). it can be written in gh flavored md and added to the repo readme.

**Comment by hugzsoubrier** [comment]
for now trying out the following: 

- Make changes and render the website 
- manually copy the docs folder to the root of repo, and rename it docs_review
- we can now comment html pages using [hypothesis](https://web.hypothes.is/)
- push the docs_review
- docs_review is used in parallel to the .qmd to make changes
- changes pushed
- the review version is used to update the original version and docs_review is deleted

**Comment by ceisenhauer** [comment]
i'm not able to see the comments left by other reviewers : ![Image](https://github.com/user-attachments/assets/0e43c1d8-3056-4684-880c-1d00027fbef5)

is this an issue of hypothesis not playing well with gh ?

**Comment by hugzsoubrier** [comment]
Ok I've added some dev guide on the README - seems to bethe right place for it but let me know if we should move this to another place.

**Comment by ceisenhauer** [comment]
thanks @hugzsoubrier ! but i can't find your changes anywhere, did you make a branch / pull request ?
